build:
  environment:
    docker: true
    postgresql: false
    redis: false
  cache:
    disabled: false
    directories:
      - vendor/
      - bower_components/
      - node_modules/
  dependencies:
    override:
      - cp .env.example .env
      - command: mysql stop
      - command: redis stop
      - command: docker-compose up -d
      - command: docker-compose run --rm web composer install --no-progress
  tests:
      - command: docker-compose run --rm app vendor/bin/phpunit
